c02zl0salvdm.lan
*** Found local files:
***   * /Users/psingh02/airflow/logs/dag_id=ETL_process/run_id=manual__2023-05-06T03:11:52.342888+00:00/task_id=feature_engineer_dataset/attempt=1.log
[2023-05-05T23:14:35.923-0400] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_process.feature_engineer_dataset manual__2023-05-06T03:11:52.342888+00:00 [queued]>
[2023-05-05T23:14:35.925-0400] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_process.feature_engineer_dataset manual__2023-05-06T03:11:52.342888+00:00 [queued]>
[2023-05-05T23:14:35.925-0400] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-05-05T23:14:35.929-0400] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): feature_engineer_dataset> on 2023-05-06 03:11:52.342888+00:00
[2023-05-05T23:14:35.932-0400] {standard_task_runner.py:57} INFO - Started process 33427 to run task
[2023-05-05T23:14:35.936-0400] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'ETL_process', 'feature_engineer_dataset', 'manual__2023-05-06T03:11:52.342888+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/data_engineer_sample.py', '--cfg-path', '/var/folders/73/mh8wnr3x3ps07jk6kk9cpp4r0000gp/T/tmp2fvv39tl']
[2023-05-05T23:14:35.937-0400] {standard_task_runner.py:85} INFO - Job 20: Subtask feature_engineer_dataset
[2023-05-05T23:14:35.957-0400] {task_command.py:410} INFO - Running <TaskInstance: ETL_process.feature_engineer_dataset manual__2023-05-06T03:11:52.342888+00:00 [running]> on host c02zl0salvdm.lan
[2023-05-05T23:14:35.977-0400] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Prateek' AIRFLOW_CTX_DAG_ID='ETL_process' AIRFLOW_CTX_TASK_ID='feature_engineer_dataset' AIRFLOW_CTX_EXECUTION_DATE='2023-05-06T03:11:52.342888+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-06T03:11:52.342888+00:00'
[2023-05-05T23:17:13.283-0400] {python.py:183} INFO - Done. Returned value was: None
[2023-05-05T23:17:13.296-0400] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=ETL_process, task_id=feature_engineer_dataset, execution_date=20230506T031152, start_date=20230506T031435, end_date=20230506T031713
[2023-05-05T23:17:13.319-0400] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-05-05T23:17:13.328-0400] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
